import os
import polars as pl

raw_data_path = "data/raw/diabetic_data.csv"

def get_column_report(df: pl.DataFrame | pl.LazyFrame) -> pl.DataFrame:
    """
    Generates a vertical summary report of all columns in a Polars DataFrame or LazyFrame.
    
    Step-by-Step Explanation of the Code:
    ---------------------------------------------------------------------------
    1. Schema Resolution:
       - 'df.collect_schema()' resolves column names and types for LazyFrames 
         without executing/loading the underlying dataset.
       - 'df.schema' reads the schema directly from eager DataFrames.
       
    2. Struct Expression Building (exprs):
       - A list comprehension builds a Polars expression for every column in the schema.
       - 'pl.struct(...)' groups multiple calculated metrics into a single structured column.
         This is highly efficient as it preserves column groupings.
       - Inside the struct:
         - 'pl.lit(col).alias("column_name")' stores the column name as a text literal.
         - 'pl.lit(str(dtype)).alias("data_type")' stores the column's data type as a text literal.
         - 'pl.col(col).null_count().alias("nulls")' aggregates the count of missing values.
         - 'pl.col(col).n_unique().alias("uniq_values")' counts distinct values in the column.
         - 'pl.len().alias("total_data")' calculates the total number of rows.
         - '(pl.col(col).null_count() / pl.len() * 100).round(2).alias("null_percentage")'
           calculates the percentage of null values, rounded to two decimal points.
       - '.alias(col)' assigns the column's original name to this structured aggregate.
       
    3. Eager vs. Lazy Execution and Pivoting:
       - 'df.select(exprs)': Computes all struct expressions in a single, parallelized, 
         multi-threaded scan across all columns.
       - If it's a LazyFrame, '.collect()' is called to optimize the query plan and 
         execute the aggregation, returning an eager DataFrame.
       - '.unpivot()' (formerly known as 'melt') rotates the wide single-row aggregated 
         metrics into a long vertical format with a 'variable' and 'value' column.
       - '.unnest("value")' unpacks the struct fields inside the 'value' column back into 
         distinct top-level columns (column_name, data_type, nulls, uniq_values, total_data, null_percentage).
       - '.drop("variable")' removes the redundant 'variable' column generated by unpivot.
    """
    # 1. Resolve schema based on frame type
    schema = df.collect_schema() if isinstance(df, pl.LazyFrame) else df.schema
    
    # 2. Build list of parallel struct aggregate expressions
    exprs = [
        pl.struct(
            pl.lit(col).alias("column_name"),
            pl.lit(str(dtype)).alias("data_type"),
            pl.col(col).null_count().alias("nulls"),
            pl.col(col).n_unique().alias("uniq_values"),
            pl.len().alias("total_data"),
            (pl.col(col).null_count() / pl.len() * 100).round(2).alias("null_percentage")
        ).alias(col)
        for col, dtype in schema.items()
    ]
    
    # 3. Select, collect if lazy, pivot (unpivot), unnest struct, and clean up
    if isinstance(df, pl.LazyFrame):
        return df.select(exprs).collect().unpivot().unnest("value").drop("variable")
    else:
        return df.select(exprs).unpivot().unnest("value").drop("variable")

def profile_data():
    if not os.path.exists(raw_data_path):
        print(f"⚠️ Raw data file not found at '{raw_data_path}' to profile.")
        return

    # Ingest CSV raw without treating '?' as null initially, so we can clean manually in memory
    df = pl.read_csv(raw_data_path)
    
    print("=== General Dataset Profile ===")
    print(f"Total Rows: {df.height}")
    print(f"Total Columns: {df.width}")
    
    # Convert string missing indicators to actual Polars nulls
    # 1. Identify all string type columns in the schema.
    # 2. Iterate and replace '?', 'None', and empty string values with None (SQL NULL equivalent)
    #    using Polars expression framework to run calculations in parallel.
    str_cols = [col for col, dtype in df.schema.items() if dtype == pl.String]
    df_cleaned = df.with_columns([
        pl.when(pl.col(col).is_in(['?', 'None', ''])).then(None).otherwise(pl.col(col)).alias(col)
        for col in str_cols
    ])
    
    print("\n=== Column-Level Data Quality Metrics (Cleaned Data) ===")
    # Generate column report on cleaned data
    column_report = get_column_report(df_cleaned)
    print(column_report)

    print("\n=== Columns with Missing Values (Sorted by Highest Null Percentage) ===")
    # Filter columns that have missing values (sorted by highest null percentage)
    missing_report = column_report.filter(pl.col("nulls") > 0).sort("null_percentage", descending=True)
    print(missing_report)

    print("\n=== Age Group Distribution ===")
    print(df_cleaned["age"].value_counts().sort("age"))

    print("\n=== Target Variable ('readmitted') Distribution ===")
    print(df_cleaned["readmitted"].value_counts())

if __name__ == "__main__":
    profile_data()
